---
# SSH key configuration
ssh_key_type: ed25519
ssh_key_mode: '0600'
ssh_dir_mode: '0700'
cleanup_ssh_key: true

# SSH options
ssh_strict_host_checking: false
ssh_user: root 
ssh_dir: "{{ ssh_user | aursu.rsync.ssh_dir }}"

# Rsync options
rsync_cleanup_target: false
rsync_owner: null
rsync_group: null
