---
- name: Generate SSH key name
  ansible.builtin.set_fact:
    key_name: "{{ target_host | aursu.rsync.generate_key_name }}"

- name: Generate SSH key path
  ansible.builtin.set_fact:
    ssh_key_path: "{{ ssh_dir }}/{{ key_name }}"

- name: Include SSH key setup tasks
  ansible.builtin.import_tasks: ssh_keys.yml

- name: Include rsync tasks
  ansible.builtin.import_tasks: rsync.yml

- name: Include cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
