---
- name: Remove target directory {{ target_dir }} on {{ target_host }} if requested
  ansible.builtin.file:
    path: "{{ target_dir }}"
    state: absent
    recurse: true
    force: true
  when: rsync_cleanup_target | default(false) | bool
  delegate_to: "{{ target_host }}"
  become: true

# Execute rsync
- name: Run rsync using generated key
  ansible.builtin.command:
    cmd: >-
      rsync -ca --info=PROGRESS2,STATS3
      {% if rsync_owner or rsync_group %}
      --chown={{ rsync_owner | default('') }}:{{ rsync_group | default('') }}
      {% endif %}
      -e "ssh -i {{ ssh_key_path }} 
      {% if not ssh_strict_host_checking %}
      -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      {% endif %}"
      {{ source_dir }}/ {{ ssh_user }}@{{ target_host }}:{{ target_dir }}
  environment:
    SSH_AUTH_SOCK: ""
  register: rsync_result
  no_log: false  # Changed to show progress output
  # Set async to a high value (in seconds) - here 12 hours
  async: 43200
  # Poll every 60 seconds
  poll: 60
