---
# Setup SSH directories and keys
- name: Ensure source .ssh directory {{ ssh_dir }} exists
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: "{{ ssh_dir_mode }}"
  become: true

# 'force: true' is set to ensure the SSH key is always (re)generated, which may overwrite existing
# keys; this is intentional to guarantee key consistency for automation.
- name: Generate SSH key pair at {{ ssh_key_path }}
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: "{{ ssh_key_type }}"
    mode: "{{ ssh_key_mode }}"
    comment: "ansible-rsync key for {{ target_host }}"
    force: true
  become: true
  register: ssh_key

- name: Read public key content for {{ ssh_key_path }}.pub
  ansible.builtin.slurp:
    src: "{{ ssh_key_path }}.pub"
  register: public_key_content
  become: true

- name: Ensure target .ssh directory {{ ssh_dir }} exists
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: "{{ ssh_dir_mode }}"
  delegate_to: "{{ target_host }}"
  run_once: true
  become: true

- name: Add public key to target's authorized_keys for user {{ ssh_user }}
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ public_key_content.content | b64decode }}"
    # rsync --server -logDtprce.iLsfxCIvu --info=STATS3 . /mnt/disks/data1
    key_options: "no-agent-forwarding,no-port-forwarding,no-pty,no-X11-forwarding"
    state: present
    manage_dir: yes
  delegate_to: "{{ target_host }}"
  become: true
