name: Sync Wiki

on:
  push:
    paths:
      - '.github/wiki/**'
    branches:
      - main

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Upload Wiki Content
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        env:
          GH_PAT: ${{ secrets.WIKI_TOKEN }}
        with:
          path: .github/wiki
          commit-message: "docs: sync wiki content"
