name: Sync Wiki

on:
  push:
    paths:
      - '.github/wiki/**'
    branches:
      - main

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Update Wiki
        env:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
        run: |
          git config --global user.email "alexander.ursu@gmail.com"
          git config --global user.name "Alexander Ursu"
          git clone "https://${WIKI_TOKEN}@github.com/aursu/ansible-collection-rsync.wiki.git" wiki
          cp -r .github/wiki/* wiki/
          cd wiki
          git add .
          git commit -m "docs: sync wiki content" || echo "No changes to commit"
          git push
